# Generated by Django 4.2.7 on 2024-03-24 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_ordermodel_elements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='items_quantity',
        ),
    ]
