# Generated by Django 4.2.7 on 2024-03-24 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_remove_ordermodel_items_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='name',
        ),
    ]
