# Generated by Django 4.2.7 on 2024-03-26 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='elements',
        ),
    ]
