# Generated by Django 4.2.7 on 2024-03-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_remove_ordermodel_elements'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='elements',
            field=models.ManyToManyField(through='customer.OrderItem', to='customer.menuitem'),
        ),
    ]
