# Generated by Django 4.2.11 on 2024-03-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_ordermodel_elements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
