# Generated by Django 4.2.11 on 2024-03-29 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_alter_cart_created_on_alter_ordermodel_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='deliver_address',
            field=models.TextField(default='adresa livrare', max_length=300),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='deliver_day',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='deliver_time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
