# Generated by Django 4.2.11 on 2024-03-29 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_ordermodel_deliver_address_ordermodel_deliver_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='elements',
        ),
    ]
