# Generated by Django 4.2.11 on 2024-03-29 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_remove_ordermodel_city_remove_ordermodel_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdata',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
