# Generated by Django 4.2.11 on 2024-03-30 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_remove_deliverdata_cake_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdata',
            name='cake_text',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customerdata',
            name='deliver_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
