# Generated by Django 4.2.11 on 2024-03-30 18:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_customerdata_cake_text_customerdata_deliver_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdata',
            name='deliver_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
