# Generated by Django 4.2.11 on 2024-04-01 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_customerdata_deliver_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverdata',
            old_name='city',
            new_name='deliver_city',
        ),
        migrations.RenameField(
            model_name='deliverdata',
            old_name='email',
            new_name='deliver_email',
        ),
        migrations.RenameField(
            model_name='deliverdata',
            old_name='name',
            new_name='deliver_name',
        ),
        migrations.RenameField(
            model_name='deliverdata',
            old_name='phone',
            new_name='deliver_phone',
        ),
        migrations.RenameField(
            model_name='deliverdata',
            old_name='state',
            new_name='deliver_state',
        ),
        migrations.RenameField(
            model_name='deliverdata',
            old_name='street',
            new_name='deliver_street',
        ),
        migrations.RenameField(
            model_name='deliverdata',
            old_name='zip_code',
            new_name='deliver_zip_code',
        ),
    ]
