# Generated by Django 4.2.11 on 2024-04-02 15:50

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_rename_city_deliverdata_deliver_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdata',
            name='deliver_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='customerdata',
            name='deliver_time',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
