# Generated by Django 4.2.11 on 2024-04-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0021_alter_customerdata_cake_text_alter_customerdata_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverdata',
            name='deliver_city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deliverdata',
            name='deliver_email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deliverdata',
            name='deliver_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deliverdata',
            name='deliver_state',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='deliverdata',
            name='deliver_street',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
